version: "3"

output: prefixed
vars:
  APP_NAME: dalle-ays
  VERSION: v0.0.0
  APP_ROOT: app
tasks:
  setup:
    prefix: setup
    desc: sets up the development environment
    cmds:
      - 'python3 -m venv venv'
      - echo activate your venv with 'source venv/bin/activate'
    sources:
      - venv

  install-deps:
    prefix: install-deps
    cmds:
      - pip install black isort
      - pip install fastapi==0.79.0 uvicorn==0.18.2 pydantic==1.9.0
      - pip install "jax[cuda]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
      - pip install -q git+https://github.com/cboin1996/dalle-mini@feat/add-wandb-api-key-auth
      - pip install -q git+https://github.com/patil-suraj/vqgan-jax@main
      - pip install pydantic[dotenv]

  build:
    prefix: build
    desc: builds the docker app
    cmds:
      - docker build -t {{.APP_NAME}}:{{.VERSION}} .

  clean:
    prefix: clean
    desc: removes the built image
    cmds:
      - docker rm {{.APP_NAME}} || true

  stop:
    prefix: stop
    desc: stops the running container
    cmds:
      - docker kill {{.APP_NAME}}

  dev:
    prefix: dev
    desc: runs the app with gpu (use -w flag for live rebuilds)
    cmds:
      - task: clean
      - task: build
      - task: run
    sources:
      - '{{.APP_ROOT}}/**'
      - '{{.APP_ROOT}}/*/**'
      - Dockerfile

  dev-cpu:
    prefix: dev
    desc: runs the app for cpu only (use -w flag for live rebuilds)
    cmds:
      - task: clean
      - task: build
      - task: run-cpu
    sources:
      - '{{.APP_ROOT}}/**'
      - '{{.APP_ROOT}}/*/**'
      - Dockerfile

  lint:
    prefix: lint
    desc: lint the application
    cmds:
      - black {{.APP_ROOT}}/.
      - isort {{.APP_ROOT}}/.
    deps: [setup]

  run:
    prefix: run
    cmds:
      - docker run --rm --name "dalle-ays" -p 8000:8000 --gpus all --env-file .env -v "${PWD}":/{{.APP_ROOT}} {{.APP_NAME}}:{{.VERSION}}

  run-cpu:
    prefix: run-cpu
      - docker run --rm --name "dalle-ays" -p 8000:8000 --env-file .env -v "${PWD}":/{{.APP_ROOT}} {{.APP_NAME}}:{{.VERSION}}
  env:
    prefix: env
    cmds:
      - echo "WANDB_API_KEY=<click here and replace this with key https://wandb.ai/authorize>"
