name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install requirements
        run: pip install ".[dev]"
      - uses: jamescurtin/isort-action@master